<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>

    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Key\**" />
    <EmbeddedResource Remove="Key\**" />
    <None Remove="Key\**" />
  </ItemGroup>

	<ItemGroup>
		<PackageReference Include="coverlet.collector" Version="6.0.2">
		  <PrivateAssets>all</PrivateAssets>
		  <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="FluentAssertions" Version="6.12.2" />
		<PackageReference Include="Microsoft.Extensions.Configuration" Version="10.0.0" />
		<PackageReference Include="Microsoft.Extensions.Configuration.Binder" Version="10.0.0" />
		<PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="10.0.0" />
		<PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.0" />
		<PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.12.0" />
		<PackageReference Include="Moq" Version="4.20.72" />
		<PackageReference Include="MSTest.TestAdapter" Version="3.6.4" />
		<PackageReference Include="MSTest.TestFramework" Version="3.6.4" />
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\..\src\FileRepository.Encrption\FileRepository.Encryption.Pgp.csproj" />
	  <ProjectReference Include="..\..\src\FileRepository.Sftp\FileRepository.Sftp.csproj" />
	  <ProjectReference Include="..\..\src\FileRepository.Zip\FileRepository.Zip.csproj" />
	  <ProjectReference Include="..\..\src\FileRepository\FileRepository.csproj" />
	</ItemGroup>

  <ItemGroup>
    <Using Include="Microsoft.VisualStudio.TestTools.UnitTesting" />
  </ItemGroup>



	<ItemGroup>
		<Content Include="Keys\*.*">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
	</ItemGroup>



	<ItemGroup>
	  <None Update="Convertors\csv\AddOnly_Employee_DCDD.csv">
	    <CopyToOutputDirectory>Always</CopyToOutputDirectory>
	  </None>
	  <None Update="Convertors\csv\test.csv">
	    <CopyToOutputDirectory>Always</CopyToOutputDirectory>
	  </None>
	</ItemGroup>


</Project>
